### PR TITLE
fix: cross-platform editor compatibility

### PR DESCRIPTION
**Pull request by DodgyTim**
These conditional compilation tweaks allow the Apple Unity Core Plugin to be included in a project which is also opened on non-Mac Unity editor platforms.

### CODE REVIEW

**Comment by kaclok** [comment]
That is  what I need.  thanks

**Comment by tomph** [comment]
Thank you @DodgyTim this is much appreciated :)

**Comment by DodgyTim** [comment]
This PR is still valid, and required if you want to have the Apple Unity Plugins in a Unity project that also builds on for Windows or other non-Apple targets.

**Comment by jonathanleang** [comment]
why's this not merged yet, I had to use this PR and another PR just to start using this. i expect more from a trillion dollar company's offical repo.

**Comment by yelbom** [comment]
I'll be much more routine and active starting Monday. Remote office hours and such @image

**Comment by jasontrask** [comment]
Thanks for this! I had to make a slight tweak as Unity complained when I tried to make an Android build (*shudders* 😂) with the macOS Unity editor.

Replacing `#if UNITY_EDITOR_OSX` with `#if UNITY_EDITOR_OSX && (UNITY_IOS || UNITY_TVOS || UNITY_STANDALONE_OSX)` in your commits fixed the issue. I'm not sure if my solution is the best fix to this though...

**Comment by DodgyTim** [comment]
@jasontrask -- thanks for finding this problem, I missed this. Once I tested this myself I realised it didn't just affect Android builds running from Unity Mac, but other non-Apple targets like WebGL.

I think your proposed fix is good, and I've updated this PR. It means a lot more files are touched, because it's not just the missing checks I originally added which need to be updated, but the existing Apple checks too.

**Comment by DodgyTim** [comment]
I've merged the changes from main... but main doesn't even *compile* at the moment thanks to a unbalanced `extern "C" {` in `plug-ins/Apple.PHASE/Native/PHASESoundEventInterface.h` :-/

**Comment by jared-marsau** [comment]
Sorry about that. Please grab ToT.

**Comment by SkyTech6** [comment]
Just to re-bump this... why was this never merged? Got hired to a project using this package and in order to even work on it I need to comment out parts of the package or write conditionals myself? That's not a good workflow with an official package from Apple.

**Comment by jonathanleang** [comment]
Can someone with write access click merge, there is no conflicts right now.

**Comment by DodgyTim** [comment]
This change still seems essential to me., but Apple doesn't seem enthusiastic to merge external PRs.

**Comment by KevinGelkingSviper** [comment]
+1   The build from the original repro just fails with various errors from within the script / swift compilation when executed from our build machine (the only Mac). With this PR I was able to successfully build.

**Comment by jrgibson** [comment]
> +1 The build from the original repro just fails with various errors from within the script / swift compilation when executed from our build machine (the only Mac). With this PR I was able to successfully build.

I _finally_ figured out why the build.pt script was failing with thousands of errors on my machine: **the build.py script failed because there was a space in a folder name in the path to this git repo!!!** Moving everything to a folder with no spaces in the name fixed those thousands of errors. 

Additionally, I did not have npm installed, which the docs say is necessary but give no info on how to find it. There are many different versions, but it seems that the best way to install npm (node package manager) is with nvm (node version manager). I used the `curl` command here to do so: https://github.com/nvm-sh/nvm#installing-and-updating

Then I think the command was something like:
`nvm —install latest`

**Comment by KevinGelkingSviper** [comment]
> > +1 The build from the original repro just fails with various errors from within the script / swift compilation when executed from our build machine (the only Mac). With this PR I was able to successfully build.
> 
> I _finally_ figured out why the build.pt script was failing with thousands of errors on my machine: **the build.py script failed because there was a space in a folder name in the path to this git repo!!!** Moving everything to a folder with no spaces in the name fixed those thousands of errors.
> 
> Additionally, I did not have npm installed, which the docs say is necessary but give no info on how to find it. There are many different versions, but it seems that the best way to install npm (node package manager) is with nvm (node version manager). I used the `curl` command here to do so: https://github.com/nvm-sh/nvm#installing-and-updating
> 
> Then I think the command was something like: `nvm —install latest`

Sadly that isn't the solution for in my case. The path is already fine (`//Users/jenkins/projects/apple-unityplugins/`), no spaces.
I've installed nvm and attempted to build with the original repo for iOS/macOS for just Core + GameKit (here's my cmd for reference) with a unity install using specifically the version from their info on github
`python3 build.py -p Core GameKit -m iOS macOS -u /Applications/Unity/Hub/Editor/2020.3.33f1 -k all -f`

This fails in various places in GameKitWrapper/GKMatchmaker.swift 🤷

**Comment by DodgyTim** [comment]
I'm not working in Unity right now, and this PR currently has (technical, not substantive) conflicts. I don't think it's ever going to be merged or the problem fixed some other way, so I'm going to close it.

All the best.

**Comment by DodgyTim** [comment]
I apologise -- I was pleased to realise that there have been equivalent changes made to the base Apple version in this commit earlier this year:
https://github.com/apple/unityplugins/commit/b4002b66f01999e4b66f609974826aaf21d59eff

Thus, this PR is no longer required. Thanks @jared-marsau!

**Pull request closed without merging**
