### PR TITLE
[Bug] Enable Bitcode by Default for GameKit

### PR DESCRIPTION
**Pull request by justadaniel**
Changing Bitcode to YES by Default will bundle the GameKit into UnityFramework preventing build errors in Xcode. This provides a more seamless experience for game developers who just want it bundled. Before hand, the only bundled framework would be for macOS.

**Example Build Errors with `ENABLE_BITCODE = NO`**
Screen Shot 2022-07-13 at 4 16 11 PM

### CODE REVIEW

**Comment by jared-marsau** [comment]
To align with the upcoming deprecation of bitcode, this change will not be taken.

For more information, please see: https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes

Changes summarized here:
> Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.

**Comment by justadaniel** [comment]
Is there a fix for the error above without using bitcode? It doesn't seem to export the .framework plugin for most of these unity plugins.

**Comment by justadaniel** [comment]
> @justadaniel I am not able to reproduce your issue. Please share with me your system config including:

**Host Mac**
Mac Mini (M1, 2020)

**Version of macOS on Host System**
macOS 12.4

**Target Device Hardware Model**
* iPhone XR
* iPad Pro 11" (M1)

**Target Device OS Version**
* iOS 16.0b3
* iPadOS 16.0b3

**Xcode Version**
14.0 Beta 3

**Unity Version**
* Game built with 2021.3.4f1 LTS
* Plugin source built with 2020.3.33f1

**Comment by jared-marsau** [comment]
Thank you. I will investigate.

**Comment by DaniBarca** [comment]
Hey guys. Is there any update on this issue? We can't get rid of these errors.

**Pull request closed without merging**
